apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mattermost-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mattermost-app
  template:
    metadata:
      labels:
        app: mattermost-app
    spec:
      containers:
      - name: app
        image: mattermost/mattermost-prod-app:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: mm-config
          mountPath: /mattermost/config
        - name: assets
          mountPath: /mattermost/data
        ports:
        - containerPort: 8065
          protocol: TCP
        env:
        - name: MATTERMOST_ENABLE_SSL
          value: "false"
        - name: DB_HOST
          value: mattermost-pg
        - name: MM_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: username
        - name: MM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: password
        resources:
          limits:
            cpu: "0.1"
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: mm-config
        configMap:
          name: mattermost-config
          items:
          - key: config.template.json
            path: config.json
      - name: assets
        gcePersistentDisk:
          pdName: mattermost-assets
          fsType: "ext4"
      restartPolicy: Always
